export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_MOVIE_CREDITS = 'GET_MOVIE_CREDITS';
export const GET_RATED_MOVIES = 'GET_RATED_MOVIES';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const GET_GENRES = 'GET_GENRES';
export const GET_IMAGES_BASE_URL = 'GET_IMAGES_BASE_URL';
